### ISSUE TITLE
프로젝트 진행 방향

### ISSUE THREAD

**Issue by zaragit** [youngjinmo/BomStart_Ex01#1]
본격적으로 작업 진행하기 전에 대략적인 진행 계획이나 방향을 정했으면 좋겠습니다!

- [x] 구현 범위
- [x] 작업 환경
- [x] 작업 진행 방법 & 업무 분담
- [x] 간략한 코드 컨벤션

**Comment by youngjinmo** [comment]
앗 안그래도 연락드리고 싶었는데, 남겨주셨네요!
- 구현범위
토비의 스프링 1장에서 나온게 사용자 등록(add)하는 DAO 밖에없었는데 저희는 사용자 등록, 조회, 수정, 제거 기능까지 구현해보면 어떨까요? 컨트롤러까지 작업해서 Postman으로 API 요청하여 CRUD 기능 확인하는것까지 해보는걸로 생각하고 있었습니다.

- 작업 환경
익숙하다보니 빌드툴은 메이븐을 사용하긴했는데, 메이븐과 그레들중 어떤걸 사용하시는게 편하신가요?
RDBMS는 h2 데이터베이스를 사용하려고 했습니다만, 사실 MySQL, Oracle 어느걸로 사용해도 상관없을것 같습니다. 어떤걸 사용하시는게 편하신가요?

- 작업 진행 및 업무 분담
제가 등록(add)랑 제거(remove)를 해도 괜찮을까요? 병주님께서 수정(update), 조회(get)해주시면 감사하겠습니다!
작업 진행은 각자 분담된 태스크를 작업하여 PR 후, 간단하게나마 리뷰하고 리팩토링이 더 필요하다면 진행후 Merge하는게 어떨까요?

- 코드 컨벤션
책을 통해 배운 개념을 테스트하는거라고 생각해서 코드 컨벤션까지는 생각하지 못했는데, 어떻게 하는게 좋을까요?
개인적으로는 인덴트의 깊이를 1까지만 하는 연습을 해보는게 좋을것 같아서 이것만 제안드리고 싶습니다.
병주님께서는 어떻게 생각하고 계신지 궁금합니다!

**Comment by zaragit** [comment]
네 좋은 의견 감사합니다.

- 구현 범위                     
프론트단 작업 없이 CRUD API 구현
- 작업 환경                     
Maven, 각자 편한 RDBMS 
- 작업 진행 및 업무 분담 
각자 @youngjinmo - (add, remove), @zaragit - (update, get) 구현하고 PR 후 Merge 하는 방식으로 진행
- 코드 컨벤션                
따로 코드 컨벤션 없이 각자 작업 후 PR을 통해서 서로 코드리뷰
